Establishment homepages
MTES-MCT/zero-logement-vacant pull request #253
Opened 2023-02-28 15:59 UTC by jrivals

2023-03-07 12:30 UTC, Falinor requested changes

2023-03-07 12:30 UTC, Falinor commented on frontend/src/store/actions/establishmentAction.tsx
> +      });
`dispatch(hideLoading());` devrait aller dans un `.finally` car en cas d'erreur, il n'est pas caché.

2023-03-07 12:30 UTC, Falinor commented on frontend/src/store/actions/establishmentAction.tsx
> +        });
Pareil : `dispatch(hideLoading());` dans un `.finally()`

2023-03-07 12:30 UTC, Falinor commented on frontend/src/views/Home/OwnerEstablishmentHomeView.tsx
> +                    {isLocality ? 'Commune' : 'Collectivités'} engagée contre la
Accord en nombre

2023-03-07 12:30 UTC, Falinor commented on frontend/src/views/Home/OwnerEstablishmentHomeView.tsx
> +                      s’engage à lutter contre la vacance au coté de l’outil 
côté

2023-03-07 14:32 UTC, jrivals commented on frontend/src/store/actions/establishmentAction.tsx
> +      });
Je suis d'accord. Je le laisse pour l'instant pour que ce soit traité globalement avec la gestion d'erreur.

2023-03-08 10:04 UTC, Falinor approved these changes

2023-03-31 14:54 UTC, merged