Invite LOVAC users from Cerema API
MTES-MCT/zero-logement-vacant pull request #712
Opened 2024-04-25 14:18 UTC by loicguillois

- Envoi les invitations chaque soir à 8h30 (heure de Paris)
- Filtre sur les dossier qui sont en statut `lovac` = true
- L'invitation est valide 7 jours. Donc un utilisateur qui ne s'inscrit jamais recevra un mail de notre part tout les 7 jours jusqu'à la création de son compte.
- Pour la mise en production, penser à ajouter les variables d'environnement:

1.  `CEREMA_ENABLE=true` 
2. `CEREMA_INVITE_LIMIT=-1` 

ainsi que la configuration Elastic (variables d'environnements). Les indexes sont déjà créés.

![image](https://github.com/MTES-MCT/zero-logement-vacant/assets/55890/d3a66db6-99ee-4c74-852d-f9e782c95585)

- Création automatique des établissements manquants
- Enregistrement de la date de la dernière exécution et du statut du script dans ELK
- Utilisation de la date de la dernière exécution avec succès stockée dans ELK pour filtrer le nombre de dossiers renvoyés par l'API

2024-05-02 09:51 UTC, Falinor requested changes

2024-05-02 09:51 UTC, Falinor commented on server/repositories/signupLinkRepository.ts
> +  const link = await db(signupLinkTable).select().where('prospect_email', email).first();
Remplacer `db(signupLinkTable)` par `SignupLinks()` pour bénéficier du typage statique et être plus résilient au changement

2024-05-02 09:51 UTC, Falinor commented on server/tasks/ceremaTask.ts
> +    if (user == null) {
Attention à bien utiliser des triples `===` pour avoir l’égalité stricte sinon Sonarcloud va gueuler

2024-05-02 09:51 UTC, Falinor commented on server/tasks/ceremaTask.ts
> +  await Promise.all(emails.map(async (email) => {
On a le module `async` (async.js) pour faciliter ce genre de chose. C’est qu’une question de style pas très importante mais ça donne ça :

`await async.forEach(email, async (email) => {`

2024-05-02 09:51 UTC, Falinor commented on server/tasks/ceremaTask.ts
> +  .catch(console.error)
On pourrait utiliser le _logger_ ici

2024-05-03 08:38 UTC, loicguillois commented on server/repositories/signupLinkRepository.ts
> +  const link = await db(signupLinkTable).select().where('prospect_email', email).first();
Les autres fonctions de ce repository font toutes appel à `db(signupLinkTable)`, je fais la modification pour les autres également ?

2024-05-16 08:54 UTC, Falinor commented on server/repositories/signupLinkRepository.ts
> +  const link = await db(signupLinkTable).select().where('prospect_email', email).first();
Oui dans l'idéal

2024-06-11 15:28 UTC, Falinor commented on server/src/infra/database/migrations/20240531083601_establishment-source.ts
> +    table.string('source').defaultTo('seed').notNullable();
Je suis pas fan d’avoir des valeurs par défaut dans la BDD, ça déplace le métier dans un fichier de migration je trouve

2024-06-11 15:28 UTC, Falinor commented on server/src/infra/elastic.ts
> +export async function getLastScriptExecutionDate(script_name: string) {
Ce serait top d’expliciter le type de retour, au cas où le code de la fonction change

2024-06-11 15:28 UTC, Falinor commented on server/src/repositories/establishmentRepository.ts
> +  logger.info('Saved establishment', { establishment: establishment.id });
Pas besoin de wrapper s’il n’y a qu’une instruction, il le fait tout seul

2024-06-11 15:28 UTC, Falinor commented on server/src/tasks/addressTask.ts
Comment on exécute les tasks ?

Ça impacte l’existence des CRON qui tournent actuellement sur Scalingo ?

2024-06-12 08:12 UTC, loicguillois commented on server/src/infra/database/migrations/20240531083601_establishment-source.ts
> +    table.string('source').defaultTo('seed').notNullable();
Ok, plutôt une requête SQL post-MEP ? je tracerais ça sur le tableau notion : https://www.notion.so/zlv/0f902ed2ec1d45db9c329395c4d49378?v=aa0c63083f824414b3b9da35b602c7e4&pvs=4

2024-06-12 08:26 UTC, loicguillois commented on server/src/tasks/addressTask.ts
j'ai mis à jour le fichier de configuration `cron.json`

2024-06-12 14:12 UTC, Falinor commented on server/src/infra/database/migrations/20240531083601_establishment-source.ts
> +    table.string('source').defaultTo('seed').notNullable();
Ce que je veux dire, c'est que pour l'insertion d'un élément `X` avec trois propriétés `a`, `b` et `c`.
Si `a` est optionnel et a une valeur par défaut dans la BDD, dans le code métier on peut passer :
```
const x: X = {
  b: 'b',
  c: 'c'
}
await repository.save(x);
response.json(x).status(201);
```

Sauf qu'en vrai, `x` contient une propriété `a` qui vaut `seed`.
Pour les tests d’API ou les tests d’intégration de la BDD par exemple, ça peut poser problème

2024-06-12 14:13 UTC, Falinor approved these changes

2024-07-09 07:45 UTC, Falinor commented on server/src/services/ceremaService/consultStructureService.ts
> +    const geoCodes = await db.raw(`select codgeo from _localities where reg='${perimeter.reg_complet[key]}'`);
> `_localities`

Cette table existe ?

> `await db.raw(select codgeo from _localities where reg='${perimeter.reg_complet[key]}')`

Ce serait top d’utiliser knex plutôt que des queries customs. Il y en a eu beaucoup par le passé qui se baladaient dans le code, ça devenait compliqué à comprendre, même si l’exemple est simple ici.

```typescript
await knex('_localities').select('codgeo').where('reg', perimeter.reg_complet[key])
```

2024-07-09 07:45 UTC, Falinor commented on server/src/services/ceremaService/consultStructureService.ts
> +export const structureToEstablishment = async (structure: Structure): Promise<EstablishmentDbo> => {
Je suis plutôt d'avis d’utiliser le mot clé `function` quand c'en est, qu’est-ce que tu en penses ?

2024-07-09 07:45 UTC, Falinor commented on server/src/tasks/ceremaTask.ts
> +}
Cette fonction existe :
```typescript
import { wait } from '@zerologementvacant/utils';
```

2024-07-09 07:45 UTC, Falinor commented on server/src/tasks/ceremaTask.ts
> +          const establishment = await db.raw(`select * from establishments where siren=${Number(structure.siret.substring(0, 9))}`);
Ça existe dans `establishmentRepository.ts` :
```typescript
await establishmentRepository.find({
  sirens: [...]
});
```

Et ça permet d’avoir un typage statique fort

2024-07-09 07:45 UTC, Falinor commented on server/src/tasks/ceremaTask.ts
> +const createEstablishment = async (establishment: { rows: string | any[]; } | undefined, structure: Structure) => {
Je comprends pas le type de `establishment` : `{ rows: string | any[]; } | undefined`
Qu’est-ce que ça représente ?

2024-07-09 08:41 UTC, loicguillois commented on server/src/services/ceremaService/consultStructureService.ts
> +    const geoCodes = await db.raw(`select codgeo from _localities where reg='${perimeter.reg_complet[key]}'`);
La table existe en production. Elle a été peuplée par le script server/src/infra/database/scripts/001-load-establishments_com_epci_reg_dep.sql

2024-07-09 12:55 UTC, merged