feat: rework secondary and archived owner display
MTES-MCT/zero-logement-vacant pull request #814
Opened 2024-07-11 13:04 UTC by loicguillois

2024-07-15 09:15 UTC, Falinor requested changes

2024-07-15 09:15 UTC, Falinor commented on frontend/src/components/OwnerCard/OwnerCard.tsx
> +              <Text size="sm" className="zlv-label-icon">
Dans l’idéal, je pense qu’il vaut mieux utiliser des styles locaux et des composants réutilisables plutôt que des styles globaux. Je crois qu’il y a un composant `Label` mais je sais pas si ça fait ce que tu veux

2024-07-15 09:15 UTC, Falinor commented on frontend/src/components/OwnerCard/OwnerCard.tsx
> +            </Text>
Étrange de wrapper un bloc texte lg avec un autre bloc texte sm

2024-07-15 09:15 UTC, Falinor commented on frontend/src/components/modals/HousingOwnersModal/HousingOwnersModal.tsx
> +    (_) => _.rank === '0' || _.rank === '-1' || _.rank === '-2'
On pourrait mettre ça dans des fonctions dans `Owner.tsx` ou même `packages/models/OwnerDTO.ts` car j’ai vu ce code dans OwnerCard.tsx à l’instant

2024-07-15 13:08 UTC, loicguillois commented on frontend/src/components/OwnerCard/OtherOwnerCard.tsx
> +        />
ça marche, c'était le code existant. Je change ça

2024-07-15 13:45 UTC, loicguillois commented on frontend/src/components/OwnerCard/OwnerCard.tsx
> +              <Text size="sm" className="zlv-label-icon">
du même avis, j'avais repris la façon de faire précédente. je change ça

2024-07-15 13:45 UTC, loicguillois commented on frontend/src/components/OwnerCard/OwnerCard.tsx
> +            </Text>
c'est le code existant, je le reprend

2024-07-15 14:11 UTC, loicguillois commented on frontend/src/components/modals/HousingOwnersModal/HousingOwnersModal.tsx
> +    (_) => _.rank === '0' || _.rank === '-1' || _.rank === '-2'
pas exactement, ici ce sont des `string` et dans OwnerCard.tsx des `number`. j'y ai pensé mais il faudrait résoudre le problème de typage en amont

2024-07-15 14:15 UTC, loicguillois commented on frontend/src/components/modals/HousingOwnersModal/HousingOwnersModal.tsx
> +    (_) => _.rank === '0' || _.rank === '-1' || _.rank === '-2'
le type de rank est en string dans `frontend/src/components/modals/HousingOwnersModal/HousingOwnersModal.tsx` et absent de `packages/models/OwnerDTO.ts`. Qu'est ce que tu en penses, correction sur PR séparée ou ici ?

2024-07-16 07:46 UTC, Falinor commented on frontend/src/components/modals/HousingOwnersModal/HousingOwnersModal.tsx
> +    (_) => _.rank === '0' || _.rank === '-1' || _.rank === '-2'
Étonnant et en même temps pas tellement...
Dans une PR séparée après LOVAC, on aura du temps pour revoir les types et **enfin** partager tous les modèles entre front et back, avec un typage fort correct !

2024-07-16 07:48 UTC, Falinor approved these changes

2024-07-31 15:26 UTC, merged