feat: LOVAC 2024 filters
MTES-MCT/zero-logement-vacant pull request #852
Opened 2024-08-08 14:21 UTC by loicguillois

2024-08-08 14:22 UTC, loicguillois commented on frontend/src/models/HousingFilters.tsx
> +  { value: 'lovac-2024', label: 'LOVAC 2024', badgeLabel: 'LOVAC 2024' },
@Falinor si tu peux me dire quelles seront les valeurs et notamment si on reste sur des nombres ou si on passe en string.

2024-08-08 15:35 UTC, Falinor requested changes

2024-08-08 15:35 UTC, Falinor commented on frontend/src/models/HousingFilters.tsx
> +  { value: 'lovac-2024', label: 'LOVAC 2024', badgeLabel: 'LOVAC 2024' },
C’est bien une string `'lovac-n'` où `n` est l’année

2024-08-08 15:35 UTC, Falinor commented on frontend/src/utils/config.ts
> +  dataYear: 2023,
Faudrait changer dans le back aussi je crois. Mais est-ce qu’on le fait avant les migrations ou après ?

2024-08-08 15:35 UTC, Falinor commented on packages/models/src/HousingFiltersDTO.ts
> +  dataYearsExcluded?: string[];
J’ai créé un nouveau champ `dataFileYears: string[]` dans l’API et `dataYears` devient déprécié. Donc il faut modifier les appels et le repository des logements

2024-08-08 16:24 UTC, loicguillois commented on frontend/src/utils/config.ts
> +  dataYear: 2023,
peut être simplement merger et mettre en prod cette PR une fois les migrations faites dans un second temps ?

2024-08-08 16:25 UTC, loicguillois commented on frontend/src/utils/config.ts
> +  dataYear: 2023,
oui effectivement `ReferenceDataFileYear` un peu plus bas

2024-08-08 16:25 UTC, loicguillois commented on frontend/src/utils/config.ts
> +  dataYear: 2023,
oui effectivement ReferenceDataFileYear un peu plus bas

2024-08-12 19:00 UTC, Falinor approved these changes

2024-09-02 14:39 UTC, merged