feat: add campaign description
MTES-MCT/zero-logement-vacant pull request #884
Opened 2024-09-17 14:50 UTC by loicguillois

2024-09-17 15:57 UTC, Falinor commented on server/src/infra/database/migrations/20240917075639_campaigns-description.ts
> +  `);
Top ! Je suis pas familier de SQL donc j’aurais écris un test mais si tu es à l’aise avec ça, pas de problème

2024-09-18 14:05 UTC, Falinor requested changes

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupAddHousingModal/GroupAddHousingModal.test.tsx
> +    const campaignTitleInputElement = screen.getAllByTestId(
`campaignTitleInputElement` devrait être `groupTitleInputElement`, ou juste `title`, ça marche aussi

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupAddHousingModal/GroupAddHousingModal.test.tsx
> +    const createButton = screen.getByTestId("create-new-group");
J’utiliserais à nouveau un sélecteur accessible, par exemple
```ts
screen.getByRole('button', {
  name: 'Créer un groupe'
})
```

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupAddHousingModal/GroupAddHousingModal.test.tsx
> +    const campaignDescriptionInputElement = screen.getAllByTestId(
`campaignDescriptionInputElement` devrait être `groupDescriptionInputElement` ou juste `description`

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    )[0];
Sélecteurs par rôle

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    const createButton = screen.getByText('Créer une campagne');
Devrait appeler un rôle `button`

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    )[0].childNodes[0] as Element;
Sélecteur par rôle

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    const save = within(modal).getByText('Confirmer');
Devrait appeler un rôle `button`

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    const createButton = screen.getByText('Créer une campagne');
Devrait appeler un rôle `button`

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    )[0].childNodes[0] as Element;
Sélecteur

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    )[0].childNodes[0] as Element;
Sélecteur

2024-09-18 14:05 UTC, Falinor commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    const save = within(modal).getByText('Confirmer');
Devrait appeler un rôle `button`

2024-09-19 08:31 UTC, loicguillois commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    const save = within(modal).getByText('Confirmer');
le composant DSFR ne permet pas d'ajouter les attributs `role` et `name` à priori.

<img width="762" alt="image" src="https://github.com/user-attachments/assets/4e41b185-fff6-4b3f-a0e9-813d780b1c30">

2024-09-19 13:28 UTC, loicguillois commented on frontend/src/components/modals/GroupCampaignCreationModal/GroupCampaignCreationModal.test.tsx
> +    const housingInfosTextElement = screen.getByTestId('housing-infos');
c'est un `<span>` , on ne peut pas lui attribuer de `name` j'ai tenté avec `screen.findByRole('alert', { name: /^Vous êtes sur le point de créer une campagne/ });` sans succès

2024-09-19 15:03 UTC, Falinor commented
Il faudrait fix les conflits et rebase la branche

2024-09-23 14:49 UTC, Falinor approved these changes

2024-09-24 15:27 UTC, loicguillois commented
tests en échecs car certainement trop lent. ils s'exécutent avec succès en local. à améliorer

2024-09-24 15:27 UTC, merged